resource_group_name   = "Anurag-RG"
location              = "East US"
vnet_name             = "Anurag-vnet01"
vnet_address_space    = "192.168.1.0/24"
subnet_name           = "subnet01"
subnet_address_prefix = "192.168.1.0/26"
nsg_name              = "nsg01"
availability_set_name = "VM01-avset"
nic_name              = "VM01-nic"
vm_name               = "POC01-vm"
vm_size               = "Standard_B2s"
admin_username        = "azureuser"
admin_password        = "Azure@12345678"

